spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5433/BookDb
spring.datasource.username=postgres
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update

server.port=8082